services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    user: node
    volumes:
      - ./app/:/home/node/app
    tty: true

  api:
    image: oven/bun:alpine
    ports:
      - "3000:3000"
    working_dir: /home/bun/api
    user: bun
    group_add:
      - "986"
    volumes:
      - ./api/:/home/bun/api
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      SERIAL_PATH: /dev/ttyUSB0
      SERIAL_BAUD_RATE: "115200"
    command: ["bun", "run", "src/index.ts"]
