services:
  nginx:
    build:
      context: ..
      dockerfile: production/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: production/Dockerfile.api
    expose:
      - "3000"
    group_add:
      - "986"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      SERIAL_PATH: /dev/ttyUSB0
      SERIAL_BAUD_RATE: "115200"
    restart: unless-stopped
